### ISSUE TITLE
llegir el funcionament de les llibreries necessàries

### ISSUE THREAD

**Issue by ArrosAmbCoses** [ArrosAmbCoses/PRA1#4]

**Comment by ArrosAmbCoses** [comment]
La llibreria que jo vaig tractar molt per damunt va ser aquesta: https://scrapy.org/

Si ho creus convenient, podríem anar deixant tota la informació que utilitzem per a cada funció a les caselles de cada funció ("Crear primera funció: [...]"), aixina podem anar consultant la feina cada vegada.

També, jo acostume a citar les fonts de codi (StackOverflow) com a comentaris dintre del codi, aixina si hi ha alguna cosa que no sabem ben bé com funciona podem anar a la discussió del fòrum.

**Comment by rogeref** [comment]
D'acord!
