### ISSUE TITLE
Llibreres

### ISSUE THREAD

**Issue by ArrosAmbCoses** [ArrosAmbCoses/PRA1#5]
Adjuntem ací les llibreries que anem utilitzant.

**Comment by ArrosAmbCoses** [comment]
Llibreria d'scrappy: https://scrapy.org/

**Comment by rogeref** [comment]
A l'scrpt  **funcio1.py** que he penjat he fet servir:
datetime: https://docs.python.org/3/library/datetime.html 
sys: https://docs.python.org/3/library/sys.html?highlight=sys#module-sys 
dateutil.relativedelta: https://dateutil.readthedocs.io/en/stable/relativedelta.html
requests: https://pypi.org/project/requests/
beautifulsoup: https://www.crummy.com/software/BeautifulSoup/bs4/doc/
