### ISSUE TITLE
Publicar a diferents branques

### ISSUE THREAD

**Issue by ArrosAmbCoses** [ArrosAmbCoses/PRA1#6]

**Comment by ArrosAmbCoses** [comment]
Tinc un amic que és dissenyador web i vaig estar comentant amb ell com funcionava github i el desenvolupament d'aplicacions en general. Em va comentar que és usual, i útil, treballar amb diferents branques de desenvolupament.

Una branca és una part de github on es guarden els arxius que fem push des del local del nostre IDE. És interessant tenir-ne més d'una perquè si hi ha alguna errada al push de l'IDE es pot esborrar tot el treball fet.

Per seguretat he creat una que es diu Treball diari. La idea és anar guardant el treball que fem dia a dia a aquesta branca, i solament passar els arxius d'aquesta, a la branca màster quan sabem que el programa funciona correctament.

Què ens pot evitar? Imagina que acabes de fer una cosa i et funciona, guardes i fas commit i push. Sense adonar-te fas push a un altre arxiu/carpeta del projecte (això substitueix la carpeta del repositori per la que tens). Això és una errada menuda però que pot esborrar projectes sense adonar-se.

En resum. Fer push de normal a la de Treball diari, i quan estem segurs que el projecte va com volem (per exemple a les reunions de cada setmana) fer push a la branca màster.

**Comment by rogeref** [comment]
Ja veig, perfecte la idea de treballar així! També ens  permet fer branques addicionals si veiem que volem provar coses addicionals (e.g. afegir funcionalitats extra sobre una base que ja funciona).
