### ISSUE TITLE
Crear primera funció: cerca aeroports

### ISSUE THREAD

**Issue by ArrosAmbCoses** [ArrosAmbCoses/PRA1#7]

**Comment by ArrosAmbCoses** [comment]
***Idea preliminar

Crec que aquesta funció hauria de tenir els paràmetres d'entrada següents: Aeroport, destí, mes, temps d'anada-tornada, dia d'eixida i nombre adults.

Exemple: València, Qualsevol destí, desembre, 3, divendres, 2.

Hauria de fer que viatgem per la pàgina a la cerca dels vols seleccionats.

**Comment by ArrosAmbCoses** [comment]
Val, se m'ocorre una manera en la que ho podem intentar fer.

Podem treballar a partir del link de ryanair. Per a la cerca que he posat d'exemple, el link a la pàgina era:
https://www.ryanair.com/es/es/cheap-flights-beta?originIata=VLC&destinationIata=ANY&isReturn=true&isMacDestination=false&promoCode=&adults=2&teens=0&children=0&infants=0&dateOut=2022-12-01&dateIn=2022-12-31&daysTrip=3&dayOfWeek=FRIDAY&isExactDate=false&outboundFromHour=00:00&outboundToHour=23:59&inboundFromHour=00:00&inboundToHour=23:59&priceValueTo=&currency=&isFlexibleDay=false

Açò crec que ho podem modificar amb codi per poder navegar on vullguem

**Comment by ArrosAmbCoses** [comment]
Crec que aquest video pot ajudar molt a resoldre el que volem: https://www.youtube.com/watch?v=kPNHKrOqedI

**Comment by rogeref** [comment]
Acabo de fer commit d'una proposta de draft de funció per generar el link a la pàgina inicial segons els paràmetres que vulguem.
M'he liat una mica sobre on escriure la descripció de com anava jaja espero que s'entengui, ja em dius si tens algun dubte.
